# Generated by Django 2.2 on 2021-09-29 07:39

from django.db import migrations, models
import recording.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cough',
            fields=[
                ('cough_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cough_record', models.FileField(upload_to=recording.models.upload_to)),
            ],
        ),
    ]
