# Generated by Django 3.1 on 2022-01-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiorecordsample',
            old_name='subjects',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='audiorecordsample',
            old_name='Time',
            new_name='upload_time',
        ),
        migrations.RenameField(
            model_name='breath',
            old_name='subjects',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='cough',
            old_name='subjects',
            new_name='subject',
        ),
    ]
