# Generated by Django 3.1 on 2021-10-29 08:32

from django.db import migrations, models
import recording.models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecordsample',
            name='audio4',
            field=models.FileField(default='', upload_to=recording.models.upload_to_audio_4),
            preserve_default=False,
        ),
    ]
