# Generated by Django 3.0 on 2022-08-03 10:06

from django.db import migrations, models
import django.db.models.deletion
import recording.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220803_1006'),
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to=recording.models.upload_to_audio_1)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('sound_type', models.CharField(choices=[('cough', 'Cough'), ('breath', 'Breath')], max_length=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Subject')),
            ],
        ),
    ]
