# Generated by Django 2.2 on 2021-10-01 07:21

from django.db import migrations, models
import django.db.models.deletion
import recording.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cough',
            name='subjects',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Subjects'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Breath',
            fields=[
                ('breath_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('breath_record', models.FileField(upload_to=recording.models.upload_to)),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Subjects')),
            ],
        ),
    ]
