# Generated by Django 2.2 on 2021-10-02 06:42

from django.db import migrations, models
import django.db.models.deletion
import recording.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('recording', '0002_auto_20211001_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecordSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('audio1', models.FileField(upload_to=recording.models.upload_to_audio_1)),
                ('audio2', models.FileField(upload_to=recording.models.upload_to_audio_2)),
                ('audio3', models.FileField(upload_to=recording.models.upload_to_audio_3)),
                ('sound_type', models.CharField(choices=[('cough', 'Cough'), ('breath', 'Breath')], max_length=10)),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Subjects')),
            ],
        ),
    ]
