version: '3.9'
services:
  web:
    image : infront/coughsoundsound-project
    build : . 
    #volumes:
    #  - ./:/code 
    environment:
      - DBHOST=dhricst.database.windows.net
      - DBPASSWORD=P@ssw0rd
      - DBPORT=
      - DBNAME=coughsounddb
      - DBUSER=cstadmin

    ports:
      - 127.0.0.1:8000:8000
        #    depends_on:
        #- db
        #restart: on-failure
        #command : python manage.py runserver 
  db:
    image : infront/mssqldev:2019
    build : ./etc/dbext
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin@123456

    
    ports:
      - 1433:1433
