# Generated by Django 3.0 on 2022-08-03 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='<span class="font-weight-bold text-dark">Rating:</span>'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='remarks',
            field=models.TextField(default=None, max_length=200, verbose_name='<span class="font-weight-bold text-dark">Feedback:</span>'),
        ),
    ]
