# Generated by Django 3.1 on 2022-01-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('1', '<span class="fa fa-star checked mr-1 text-left" style="color:orange"></span>'), ('2', '<span class="fa fa-star checked mr-1 text-left" style="color:orange"></span><span class="fa fa-star checked mr-1 text-left" style="color:orange"></span>'), ('3', '<span class="fa fa-star checked mr-1 text-left" style="color:orange"></span><span class="fa fa-star checked mr-1 text-left" style="color:orange"></span><span class="fa fa-star checked mr-1 text-left" style="color:orange"></span>'), ('4', '<span class="fa fa-star checked mr-1 text-left" style="color:orange"></span><span class="fa fa-star checked mr-1 text-left" style="color:orange"></span><span class="fa fa-star checked mr-1 text-left" style="color:orange"></span><span class="fa fa-star checked mr-1 text-left" style="color:orange"></span>'), ('5', '<span class="fa fa-star checked mr-1 text-left" style="color:orange"></span><span class="fa fa-star checked mr-1 text-left" style="color:orange"></span><span class="fa fa-star checked mr-1 text-left" style="color:orange"></span><span class="fa fa-star checked mr-1 text-left" style="color:orange"></span><span class="fa fa-star checked mr-1 text-left" style="color:orange"></span>')], default=None, max_length=200, verbose_name='<span class="font-weight-bold text-dark">Rating:</span>'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='remarks',
            field=models.TextField(default=None, max_length=200, verbose_name='<span class="font-weight-bold text-dark">Description:</span>'),
        ),
    ]
