# Generated by Django 3.1 on 2022-01-03 10:39

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionnairedata',
            fields=[
                ('questionid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('respondent_choices', models.CharField(choices=[('healthy', 'Healthy individual (never been infected)'), ('positive', 'COVID-19 currently positive'), ('negative', 'COVID-19 recovered')], default='', max_length=50, verbose_name='1. Which group of respondents do you belong to?')),
                ('respondent_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=50, verbose_name='2. What is your biological sex?')),
                ('age', models.IntegerField(verbose_name='How old are you?')),
                ('med_cond_opt', multiselectfield.db.fields.MultiSelectField(choices=[('none', 'None'), ('asthma', 'Asthma'), ('cystic', 'Cystic Fibrosis'), ('copd', 'COPD/Emphysema'), ('pulmonary', 'Pulmonary Fibrosis'), ('lung', 'Other lung diseases'), ('hbp', 'High Blood Pressure'), ('angina', 'Angina'), ('stroke', 'Previous Stroke or Transient ischemic attack'), ('heartattack', 'Previous heart attack'), ('valvular', 'Valvular heart disease'), ('other', 'Other heart disease'), ('diabetes', 'Diabetes'), ('cancer', 'Cancer'), ('organ', 'Previous organ transplant'), ('hiv', 'HIV or impaired immune system'), ('longterm', 'Other long-term condition')], default=False, max_length=118, verbose_name='3. Do you have any of these medical conditions? (can choose more than one)')),
                ('respondent_smoke', multiselectfield.db.fields.MultiSelectField(choices=[('never', 'Never smoked'), ('exsmoker', 'Ex-smoker'), ('current1', 'Current smoker (less than one a day)'), ('current2', 'Current smoker (1 to 10 cigarettes per day)'), ('current3', 'Current smoker (11 to 20 cigarettes per day)'), ('current4', 'Current smoker (21+ cigarettes per day)'), ('current5', 'Current smoker (e-cigarettes only)')], default=False, max_length=59, verbose_name='4. Do you, or have you, ever smoked (including e-cigarettes)?')),
                ('symptoms_opt', multiselectfield.db.fields.MultiSelectField(choices=[('none', 'None'), ('fever', 'Fever (feeling feverish or warmer than usual)'), ('chills', 'Chills'), ('drycough', 'Dry cough'), ('wetcough', 'Wet cough'), ('difficultbreath', 'Difficult breathing or feeling shortness of breath'), ('chestpain', 'Chest pain'), ('losstastesmell', 'Loss of taste or smell'), ('confusion', 'Confusion'), ('dizzy', 'Dizziness or vertigo'), ('headache', 'Headache'), ('muscleache', 'Muscle aches'), ('sorethroat', 'Sore throat, runny and blocked nose')], default=False, max_length=123, verbose_name='5. Do you have the following symptoms irrespective of having confirmed with COVID-19 or not? (can choose more than one)')),
                ('date_diagnosed', models.DateField(blank=True, default=None, null=True, verbose_name='When were you diagnosed positive for COVID-19? ')),
                ('vaccinated', models.CharField(choices=[('vaccinated', 'Vaccinated'), ('not vaccinated', 'Not Vaccinated')], default='', max_length=50, verbose_name='Your vaccination status?')),
                ('date_vaccinated', models.DateField(blank=True, default=None, null=True, verbose_name='Date of last vaccine dose (including booster dose)')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects')),
            ],
        ),
    ]
