# Generated by Django 3.1 on 2021-10-29 08:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='med_cond_opt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('none', 'None'), ('asthma', 'Asthma'), ('cystic', 'Cystic Fibrosis'), ('copd', 'COPD/Emphysema'), ('pulmonary', 'Pulmonary Fibrosis'), ('lung', 'Other lung diseases'), ('hbp', 'High Blood Pressure'), ('angina', 'Angina'), ('stroke', 'Previous Stroke or Transient ischemic attack'), ('heartattack', 'Previous heart attack'), ('valvular', 'Valvular heart disease'), ('other', 'Other heart disease'), ('diabetes', 'Diabetes'), ('cancer', 'Cancer'), ('organ', 'Previous organ transplant'), ('hiv', 'HIV or impaired immune system'), ('longterm', 'Other long-term condition')], default=False, max_length=118, verbose_name='Do you have any of these medical conditions? (can choose more than one)'),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=50, verbose_name='What is your biological sex?'),
        ),
    ]
