# Generated by Django 3.0 on 2022-08-03 10:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnairedata',
            name='date_diagnosed',
        ),
        migrations.RemoveField(
            model_name='questionnairedata',
            name='date_vaccinated',
        ),
        migrations.RemoveField(
            model_name='questionnairedata',
            name='respondent_choices',
        ),
        migrations.RemoveField(
            model_name='questionnairedata',
            name='respondent_smoke',
        ),
        migrations.RemoveField(
            model_name='questionnairedata',
            name='vaccinated',
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='age',
            field=models.PositiveIntegerField(verbose_name='2. How old are you?'),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='med_cond_opt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('none', 'None'), ('asthma', 'Asthma'), ('cystic', 'Cystic Fibrosis'), ('copd', 'COPD/Emphysema'), ('pulmonary', 'Pulmonary Fibrosis'), ('lung', 'Other lung diseases'), ('hbp', 'High Blood Pressure'), ('angina', 'Angina'), ('stroke', 'Previous Stroke or Transient ischemic attack'), ('heartattack', 'Previous heart attack'), ('valvular', 'Valvular heart disease'), ('other', 'Other heart disease'), ('diabetes', 'Diabetes'), ('cancer', 'Cancer'), ('organ', 'Previous organ transplant'), ('hiv', 'HIV or impaired immune system'), ('longterm', 'Other long-term condition')], default=False, max_length=118, verbose_name='3. Do you have any of these medical conditions (can choose more than one)?'),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=50, verbose_name='1. What is your biological sex?'),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='symptoms_opt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('none', 'None'), ('fever', 'Fever (feeling feverish or warmer than usual)'), ('chills', 'Chills'), ('drycough', 'Dry cough'), ('wetcough', 'Wet cough'), ('difficultbreath', 'Difficult breathing or feeling shortness of breath'), ('chestpain', 'Chest pain'), ('losstastesmell', 'Loss of taste or smell'), ('confusion', 'Confusion'), ('dizzy', 'Dizziness or vertigo'), ('headache', 'Headache'), ('muscleache', 'Muscle aches'), ('sorethroat', 'Sore throat, runny and blocked nose')], default=False, max_length=123, verbose_name='4. Do you have the following symptoms irrespective of having confirmed with COVID-19 or not (can choose more than one)?'),
        ),
    ]
