# Generated by Django 2.2 on 2021-10-05 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_questionnairedata_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Subjects'),
        ),
    ]
