# Generated by Django 2.2 on 2021-10-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20211007_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_choices',
            field=models.CharField(choices=[('healthy', 'Healthy individual'), ('positive', 'COVID-19 (currently positive)'), ('tuberculosis', 'Tuberculosis'), ('pnuemonia', 'Pnuemonia (not due to COVID-19)')], default='', max_length=50, verbose_name='Which group of respondents you are?'),
        ),
    ]
