# Generated by Django 2.2 on 2021-10-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20211007_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='date_diagnosed',
            field=models.CharField(choices=[('none', 'none'), ('last14days', 'Within last 14 days'), ('morethan14days', 'More than 14 days ago, less than 3 months'), ('morethan3m', 'More than 3 months, less than 1 year'), ('morethan1y', 'More than 1 year ago')], default='', max_length=100, verbose_name='When was you being diagnosed for that infection? '),
        ),
    ]
