# Generated by Django 4.0 on 2022-10-03 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
            ],
        ),
    ]
