# Generated by Django 2.2 on 2021-09-29 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subjects_id',
            field=models.UUIDField(default=uuid.UUID('14032376-a093-4633-b2ce-e34837319633'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
