# Generated by Django 2.2 on 2021-09-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Staff', 'Staff')], max_length=20),
        ),
    ]
