# Generated by Django 3.1 on 2022-01-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220119_2218'),
        ('questionnaire', '0001_initial'),
        ('recording', '0002_auto_20220119_2218'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subjects_id',
            new_name='subject_id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subjects_login',
            new_name='subject_login',
        ),
    ]
