# Generated by Django 3.0 on 2022-08-03 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Please use a correct contact number format (01XXXXXXX). Up to 11 Digits', regex='^(01)[0-46-9]-*[0-9]{7,8}$')], verbose_name='Phone Number:'),
        ),
    ]
