# Generated by Django 2.2 on 2021-09-29 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210927_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subjects_id', models.UUIDField(default=uuid.UUID('5ee8048f-3540-4a83-8eda-23fad638c24a'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('subjects_login', models.CharField(max_length=50, null=True, unique=True)),
                ('subjects_phone_number', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
