# Generated by Django 2.2 on 2021-10-04 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211004_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subjects_phone_number',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+?6?01)[0-46-9]-*[0-9]{7,8}$')]),
        ),
    ]
