# Generated by Django 3.1 on 2021-10-26 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211005_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='subjects_phone_number',
        ),
        migrations.AddField(
            model_name='subjects',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+60'. Up to 15 digits allowed.", regex='^(\\+?6?01)[0-46-9]-*[0-9]{7,8}$')], verbose_name='Phone Number'),
        ),
    ]
