"""
Django settings for mohcough project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
import sys

sys.modules['fontawesome_free'] = __import__('fontawesome-free')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nxni+&g$@b@vyz)#i-z7-(($rsr27)6z%a8&a9x2nu@@j%fvll'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '0.0.0.0',
                'localhost', '20.212.39.73', 'cst-c19.southeastasia.cloudapp.azure.com', 'cough.infrontconsulting.asia', 'coughsound.dhri.my']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'fontawesome_free',
    'crispy_forms',
    'multiselectfield',
    'accounts', #local account
    'questionnaire',
    'recording',
    'common',
    'result',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mohcough.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mohcough.wsgi.application'
CRISPY_TEMPLATE_PACK = 'bootstrap4'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(os.path.join(BASE_DIR, "db.sqlite3")),
        }
    }
else:
    DATABASES = {
    'default': {
            'ENGINE': 'mssql',
            'HOST': 'dhricst.database.windows.net',
            'PORT': '',
            'NAME': 'coughsounddb',
            'USER': 'cstadmin', 
            'PASSWORD': 'P@ssw0rd', 
            'OPTIONS': {
                'driver': "ODBC Driver 17 for SQL Server",
                'unicode_results': True,
            },
        },
    }

    DATABASES = {
    'default': {
            'ENGINE': 'sql_server.pyodbc',
            'HOST': os.environ['DBHOST'],
            'PORT': '',
            'NAME': os.environ['DBNAME'],
            'USER': os.environ['DBUSER'], 
            'PASSWORD': os.environ['DBPASSWORD'],
            'OPTIONS': {
                'driver': "ODBC Driver 17 for SQL Server",
                'unicode_results': True,
            },
        },
    }

DATABASES = {
'default': {
        'ENGINE': 'mssql',
        'HOST': os.environ['DBHOST'],
        'PORT': '',
        'NAME': os.environ['DBNAME'],
        'USER': os.environ['DBUSER'], 
        'PASSWORD': os.environ['DBPASSWORD'],
        'OPTIONS': {
            'driver': "ODBC Driver 17 for SQL Server",
            'unicode_results': True,
        },
    },
}
# DATABASES = {
# 'default': {
#         'ENGINE': 'mssql',
#         'HOST': os.environ['DBHOST'],
#         'PORT': os.environ['DBPORT'],
#         'NAME': os.environ['DBNAME'],
#         'USER': os.environ['DBUSER'], 
#         'PASSWORD': os.environ['DBPASSWORD'],
#         'OPTIONS': {
#             'driver': "ODBC Driver 17 for SQL Server",
#             'unicode_results': True,
#         },
#     },
# }
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'accounts.Account'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
        'django.contrib.auth.backends.ModelBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ms'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_L10N = True

USE_TZ = False 

# Add custom languages not provided by Django
# import django.conf.locale
# from django.conf import global_settings
# LANG_INFO = dict(django.conf.locale.LANG_INFO, **EXTRA_LANG_INFO)
# django.conf.locale.LANG_INFO = LANG_INFO

EXTRA_LANG_INFO = {
    'ms': {
        'bidi': False, # right-to-left
        'code': 'ms',
        'name': 'Bahasa Melayu',
        'name_local': u'Bahasa Melayu', #unicode codepoints here
    },
}

# Add custom languages not provided by Django

LANGUAGES = (
    ('en', _('English')),
    # ('id', _('Bahasa Indonesia')),
    ("ms", _("Bahasa Malaysia")),
    ('zh-hans', _('Simplified Chinese')),

)
import django.conf.locale
from django.conf import global_settings

django.conf.locale.LANG_INFO.update(EXTRA_LANG_INFO)

global_settings.LANGUAGES += ("ms", _("Bahasa Melayu"))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

if not DEBUG:
    AZURE_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=coughsoundadls;AccountKey=a3leb87q8xM1h42lp+iBwT69aWpdLLRvAWL/rbhl+7lvs6piivdwgbZWsm3Rpy4VytuDOTlKD6cuiDi7jqZ7Xg==;EndpointSuffix=core.windows.net"
    AZURE_CONTAINER = 'coughsoundproject' # Container or File System Name
    DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'

# CELERY SETTINGS
CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_RESULT_BACKEND = "redis://localhost:6379"
