# Generated by Django 3.0.1 on 2021-09-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questionnairedata',
            fields=[
                ('questionid', models.BigAutoField(primary_key=True, serialize=False)),
                ('respondent_choices', models.CharField(choices=[('healthy', 'Healthy individual'), ('positive', 'COVID-19 (currently positive)'), ('tuberculosis', 'Tuberculosis'), ('pnuemonia', 'Pnuemonia (not due to COVID-19)')], max_length=50)),
                ('respondent_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('med_cond_opt', models.CharField(choices=[('none', 'None'), ('asthma', 'Asthma'), ('cystic', 'Cystic Fibrosis'), ('copd', 'COPD/Emphysema'), ('pulmonary', 'Pulmonary Fibrosis'), ('lung', 'Other lung diseases'), ('hbp', 'High Blood Pressure'), ('angina', 'Angina'), ('stroke', 'Previous Stroke or Transient ischemic attack'), ('heartattack', 'Previous heart attack'), ('valvular', 'Valvular heart disease'), ('other', 'Other heart disease'), ('diabetes', 'Diabetes'), ('cancer', 'Cancer'), ('organ', 'Previous organ transplant'), ('hiv', 'HIV or impaired immune system'), ('longterm', 'Other long-term condition')], max_length=100)),
                ('respondent_smoke', models.CharField(choices=[('never', 'Never smoked'), ('exsmoker', 'Ex-smoker'), ('current1', 'Current smoker (less than one a day)'), ('current2', 'Current smoker (1 to 10 cigarettes per day'), ('current3', 'Current smoker (11 to 20 cigarettes per day'), ('current4', 'Current smoker (21+ cigarettes per day'), ('current5', 'Current smoker (e-cigarettes only)')], max_length=100)),
                ('symptoms_opt', models.CharField(choices=[('none', 'None'), ('fever', 'Fever (feeling feverish or warmer than usual)'), ('chills', 'Chills'), ('drycough', 'Dry cough'), ('wetcough', 'Wet cough'), ('difficultbreath', 'Difficult breathing or feeling shortness of breath'), ('chestpain', 'Chest pain'), ('losstastesmell', 'Loss of taste or smell'), ('confusion', 'Confusion'), ('dizzy', 'Dizziness or vertigo'), ('headache', 'Headache'), ('muscleache', 'Muscle aches'), ('sorethroat', 'Sore throat, runny and blocked nose')], max_length=100)),
            ],
        ),
    ]
