# Generated by Django 2.1.15 on 2021-09-23 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('75be7f3b-a099-44bd-9a9a-7f56f9f408cb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
