# Generated by Django 2.2 on 2021-09-23 03:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('86ed6a88-45f9-485a-b43b-c7f7757db2fc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
