# Generated by Django 2.2 on 2021-09-27 04:39

from django.db import migrations, models
import subjects.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cough',
            name='cough_id',
            field=models.UUIDField(default=uuid.UUID('7d47649b-8e4d-42a1-ba38-c65e02acade1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cough',
            name='cough_record',
            field=models.FileField(upload_to=subjects.models.upload_to),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('ae7b510b-f387-4b41-9b89-ad49cf7a7943'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
