# Generated by Django 3.0.1 on 2021-09-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='age',
            field=models.IntegerField(),
        ),
    ]
