# Generated by Django 2.2 on 2021-09-29 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cough',
            name='cough_id',
            field=models.UUIDField(default=uuid.UUID('07fb7e19-f373-4d28-a843-37e8f25fff2f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('72907f92-23ac-4553-8630-45c4d3dffb1d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
