# Generated by Django 2.1.15 on 2021-09-23 05:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20210923_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('72717bf1-21f3-47b9-9b0c-10ba36c06da1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
