# Generated by Django 2.2 on 2021-09-23 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20210923_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cough',
            fields=[
                ('cough_id', models.UUIDField(default=uuid.UUID('70bebdd1-44bb-4a22-a9f8-1eaa727a0a2f'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('cough_record', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('24d46a02-2475-4fe9-8089-1b98a2ed1400'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
