# Generated by Django 3.0.1 on 2021-09-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20210914_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairedata',
            name='date_diagnosed',
            field=models.CharField(choices=[('last14days', 'Within last 14 days'), ('morethan14days', 'More than 14 days ago, less than 3 months'), ('morethan3m', 'More than 3 months, less than 1 year'), ('morethan1y', 'More than 1 year ago')], default='Within last 14 days', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_choices',
            field=models.CharField(choices=[('healthy', 'Healthy individual'), ('positive', 'COVID-19 (currently positive)'), ('tuberculosis', 'Tuberculosis'), ('pnuemonia', 'Pnuemonia (not due to COVID-19)')], max_length=50, verbose_name='Which group of respondents you are?'),
        ),
    ]
