# Generated by Django 2.1.15 on 2021-09-23 05:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20210923_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('04e72f5f-26ea-406a-9083-34b7eeb91e34'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
