# Generated by Django 3.0.1 on 2021-09-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20210915_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='date_diagnosed',
            field=models.CharField(choices=[('last14days', 'Within last 14 days'), ('morethan14days', 'More than 14 days ago, less than 3 months'), ('morethan3m', 'More than 3 months, less than 1 year'), ('morethan1y', 'More than 1 year ago')], default='', max_length=100, verbose_name='When was you being diagnosed for that infection? '),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='med_cond_opt',
            field=models.CharField(choices=[('none', 'None'), ('asthma', 'Asthma'), ('cystic', 'Cystic Fibrosis'), ('copd', 'COPD/Emphysema'), ('pulmonary', 'Pulmonary Fibrosis'), ('lung', 'Other lung diseases'), ('hbp', 'High Blood Pressure'), ('angina', 'Angina'), ('stroke', 'Previous Stroke or Transient ischemic attack'), ('heartattack', 'Previous heart attack'), ('valvular', 'Valvular heart disease'), ('other', 'Other heart disease'), ('diabetes', 'Diabetes'), ('cancer', 'Cancer'), ('organ', 'Previous organ transplant'), ('hiv', 'HIV or impaired immune system'), ('longterm', 'Other long-term condition')], default='', max_length=100, verbose_name=' Do you have any of these medical conditions? (can choose more than one)'),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_choices',
            field=models.CharField(choices=[('healthy', 'Healthy individual'), ('positive', 'COVID-19 (currently positive)'), ('tuberculosis', 'Tuberculosis'), ('pnuemonia', 'Pnuemonia (not due to COVID-19)')], default='', max_length=50, verbose_name='Which group of respondents you are?'),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=50, verbose_name='What is your biological sex?'),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_smoke',
            field=models.CharField(choices=[('never', 'Never smoked'), ('exsmoker', 'Ex-smoker'), ('current1', 'Current smoker (less than one a day)'), ('current2', 'Current smoker (1 to 10 cigarettes per day'), ('current3', 'Current smoker (11 to 20 cigarettes per day'), ('current4', 'Current smoker (21+ cigarettes per day'), ('current5', 'Current smoker (e-cigarettes only)')], default='', max_length=100, verbose_name='Do you, or have you, ever smoked (including e-cigarettes)?'),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='symptoms_opt',
            field=models.CharField(choices=[('none', 'None'), ('fever', 'Fever (feeling feverish or warmer than usual)'), ('chills', 'Chills'), ('drycough', 'Dry cough'), ('wetcough', 'Wet cough'), ('difficultbreath', 'Difficult breathing or feeling shortness of breath'), ('chestpain', 'Chest pain'), ('losstastesmell', 'Loss of taste or smell'), ('confusion', 'Confusion'), ('dizzy', 'Dizziness or vertigo'), ('headache', 'Headache'), ('muscleache', 'Muscle aches'), ('sorethroat', 'Sore throat, runny and blocked nose')], default='', max_length=100, verbose_name='Do you have the following symptoms irrespective of having confirmed with COVID-19 or not? (can choose more than one)'),
        ),
    ]
