# Generated by Django 2.1.15 on 2021-09-23 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20210923_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('e6d6ae11-40b5-4669-a0a0-8ab8d76ca6f9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
