# Generated by Django 3.0.1 on 2021-09-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20210917_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_smoke',
            field=models.CharField(choices=[('never', 'Never smoked'), ('exsmoker', 'Ex-smoker'), ('current1', 'Current smoker (less than one a day)'), ('current2', 'Current smoker (1 to 10 cigarettes per day)'), ('current3', 'Current smoker (11 to 20 cigarettes per day)'), ('current4', 'Current smoker (21+ cigarettes per day)'), ('current5', 'Current smoker (e-cigarettes only)')], default='', max_length=100, verbose_name='Do you, or have you, ever smoked (including e-cigarettes)?'),
        ),
    ]
