# Generated by Django 2.1.15 on 2021-09-23 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20210923_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('9977112b-0363-43fe-bc29-2f82edac9e27'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
