# Generated by Django 2.1.15 on 2021-09-23 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20210923_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('e3ce9f2d-5484-4cb4-a465-2868433ea407'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
