# Generated by Django 2.1.15 on 2021-09-23 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20210923_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('4cb30d96-a5ac-4ff3-8e40-5db44b2d4616'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
