# Generated by Django 2.1.15 on 2021-09-23 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_auto_20210923_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('e98d79ca-d965-47a5-b7e0-ec042ad98f41'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
