# Generated by Django 2.1.15 on 2021-09-23 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_auto_20210923_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('d2c94fdc-9559-4688-bb38-a65180265232'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
