# Generated by Django 3.0.1 on 2021-09-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_auto_20210919_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='med_cond_opt',
            field=models.BooleanField(default=False, verbose_name=' Do you have any of these medical conditions? (can choose more than one)'),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=50, verbose_name='\n What is your biological sex?'),
        ),
    ]
