# Generated by Django 2.1.15 on 2021-09-23 07:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_auto_20210923_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('79a67b10-db93-4737-9b6c-b9296a69a8d9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_choices',
            field=models.CharField(choices=[('Healthy individual', 'healthy'), ('COVID-19 (currently positive)', 'positive'), ('Tuberculosis', 'tuberculosis'), ('Pnuemonia (not due to COVID-19)', 'pnuemonia')], default='', max_length=50, verbose_name='Which group of respondents you are?'),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_sex',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='', max_length=50, verbose_name=' What is your biological sex?'),
        ),
    ]
