# Generated by Django 3.0.1 on 2021-09-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_auto_20210919_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=50, verbose_name=' What is your biological sex?'),
        ),
    ]
