# Generated by Django 2.1.15 on 2021-09-23 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_auto_20210923_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('000bdf03-35a4-4d44-98b2-32b459a1aaeb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=50, verbose_name=' What is your biological sex?'),
        ),
    ]
