# Generated by Django 2.1.15 on 2021-09-23 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_auto_20210923_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('75546768-73d4-4073-9e2d-0c789011c90c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_choices',
            field=models.CharField(choices=[('healthy', 'Healthy individual'), ('positive', 'COVID-19 (currently positive)'), ('tuberculosis', 'Tuberculosis'), ('pnuemonia', 'Pnuemonia (not due to COVID-19)')], default='', max_length=50, verbose_name='Which group of respondents you are?'),
        ),
    ]
