# Generated by Django 2.1.15 on 2021-09-23 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_auto_20210923_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='date_diagnosed',
            field=models.CharField(choices=[('Within last 14 days', 'last14days'), ('More than 14 days ago, less than 3 months', 'morethan14days'), ('More than 3 months, less than 1 year', 'morethan3m'), ('More than 1 year ago', 'morethan1y')], default='', max_length=100, verbose_name='When was you being diagnosed for that infection? '),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('dc8e18bb-2edc-4f78-baa7-8563dcca7a8b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_smoke',
            field=models.CharField(choices=[('Never smoked', 'never'), ('Ex-smoker', 'exsmoker'), ('Current smoker (less than one a day)', 'current1'), ('Current smoker (1 to 10 cigarettes per day)', 'current2'), ('Current smoker (11 to 20 cigarettes per day)', 'current3'), ('Current smoker (21+ cigarettes per day)', 'current4'), ('Current smoker (e-cigarettes only)', 'current5')], default='', max_length=100, verbose_name='Do you, or have you, ever smoked (including e-cigarettes)?'),
        ),
    ]
