# Generated by Django 3.0.1 on 2021-09-21 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_auto_20210921_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('c0ced109-14fb-4e3c-a180-5cd3cd24995a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
