# Generated by Django 2.1.15 on 2021-09-23 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_auto_20210923_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='date_diagnosed',
            field=models.CharField(choices=[('last14days', 'Within last 14 days'), ('morethan14days', 'More than 14 days ago, less than 3 months'), ('morethan3m', 'More than 3 months, less than 1 year'), ('morethan1y', 'More than 1 year ago')], default='', max_length=100, verbose_name='When was you being diagnosed for that infection? '),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('70ed4115-9c1a-4123-a739-3428c4f94690'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questionnairedata',
            name='respondent_smoke',
            field=models.CharField(choices=[('never', 'Never smoked'), ('exsmoker', 'Ex-smoker'), ('current1', 'Current smoker (less than one a day)'), ('current2', 'Current smoker (1 to 10 cigarettes per day)'), ('current3', 'Current smoker (11 to 20 cigarettes per day)'), ('current4', 'Current smoker (21+ cigarettes per day)'), ('current5', 'Current smoker (e-cigarettes only)')], default='', max_length=100, verbose_name='Do you, or have you, ever smoked (including e-cigarettes)?'),
        ),
    ]
