# Generated by Django 2.1.15 on 2021-09-23 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_auto_20210923_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedata',
            name='questionid',
            field=models.UUIDField(default=uuid.UUID('02718774-0ce0-4f8c-9081-d57f03d4ae88'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
