# Generated by Django 2.1.15 on 2021-09-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0016_auto_20210923_1545'),
        ('subjects', '0003_auto_20210923_0739'),
    ]

    operations = [
    ]
